version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: financial-tracker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-financial_tracker}
      MYSQL_USER: ${MYSQL_USER:-financial_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-financial_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - financial-tracker-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-tracker-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-financial_user}:${MYSQL_PASSWORD:-financial_password}@mysql:3306/${MYSQL_DATABASE:-financial_tracker}"
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production-make-it-very-long-and-random}
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: "http://localhost:3000"
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - financial-tracker-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (Optional - for development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: financial-tracker-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: "http://localhost:3001/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - financial-tracker-network

volumes:
  mysql_data:

networks:
  financial-tracker-network:
    driver: bridge 