version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: financial-tracker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-financial_tracker}
      MYSQL_USER: ${MYSQL_USER:-financial_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-financial_password}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-init:/docker-entrypoint-initdb.d
    networks:
      - financial-tracker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER:-financial_user}", "-p${MYSQL_PASSWORD:-financial_password}"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-tracker-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-financial_user}:${MYSQL_PASSWORD:-financial_password}@mysql:3306/${MYSQL_DATABASE:-financial_tracker}"
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production-make-it-very-long-and-random-production-2024}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${BACKEND_PORT:-8001}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8000}
    ports:
      - "${BACKEND_PORT:-8001}:${BACKEND_PORT:-8001}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - financial-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-8001}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8001/api}
    container_name: financial-tracker-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8001/api}
    ports:
      - "${FRONTEND_PORT:-8000}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - financial-tracker-network

volumes:
  mysql_data:

networks:
  financial-tracker-network:
    driver: bridge 