version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-tracker-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production-make-it-very-long-and-random-production-2024}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${BACKEND_PORT:-8001}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8000}
    ports:
      - "${BACKEND_PORT:-8001}:${BACKEND_PORT:-8001}"
    networks:
      - financial-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-8001}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8001/api}
    container_name: financial-tracker-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8001/api}
    ports:
      - "${FRONTEND_PORT:-8000}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    driver: bridge 